## Objectives
* to learn to access values of n-dimensional arrays efficiently.

Using a for loop is not allowed in this exercise.

1. Generate a 2-dimensional array of size 9x9, with all elements initialized to 1 and of type int8.

In [115]:
import numpy as np

arr = np.ones((9, 9), dtype=np.int8)

print(arr)

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


Using slicing, create the following array:

```
array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 1, 1, 1, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 0, 0, 1, 0, 1],
    [1, 0, 1, 1, 1, 1, 1, 0, 1],
    [1, 0, 0, 0, 0, 0, 0, 0, 1],
    [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=np.int8)

In [119]:
arr[1:8, 1:8] = 0
arr[2:7, 2:7] = 1
arr[3:6, 3:6] = 0
arr[4:5, 4:5] = 1

print(arr)

[[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


3. Using broadcasting create an output matrix based on the following two arrays:

```
array_1 = np.array([1,2,3,4,5], dytpe=np.int8)
array_2 = np.array([1,2,3], dytpe=np.int8)

In [143]:
import numpy as np

# Create the two arrays (note: fixed typo 'dytpe' -> 'dtype')
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
array_2 = np.array([1, 2, 3], dtype=np.int8)

print("array_1 shape:", array_1.shape)
print("array_1:", array_1)
print("\narray_2 shape:", array_2.shape)
print("array_2:", array_2)

# Reshape arrays to enable broadcasting
# array_1 becomes a column vector (5, 1)
# array_2 remains a row vector (3,)
array_1_col = array_1[:, np.newaxis]  # or array_1.reshape(-1, 1)

print("\n" + "="*50)
print("BROADCASTING EXAMPLES")
print("="*50)

# Example 1: Addition
print("\n1. Addition (array_1_col + array_2):")
result_add = array_1_col + array_2
print(result_add)

# Example 2: Multiplication
print("\n2. Multiplication (array_1_col * array_2):")
result_mul = array_1_col * array_2
print(result_mul)

# Example 3: Outer product-style operation
print("\n3. Subtraction (array_1_col - array_2):")
result_sub = array_1_col - array_2
print(result_sub)

# Example 4: Division
print("\n4. Division (array_1_col / array_2):")
result_div = array_1_col / array_2
print(result_div)

print("\n" + "="*50)
print("Output matrix shape:", result_add.shape)
print("Output matrix dtype:", result_add.dtype)

array_1 shape: (5,)
array_1: [1 2 3 4 5]

array_2 shape: (3,)
array_2: [1 2 3]

BROADCASTING EXAMPLES

1. Addition (array_1_col + array_2):
[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]

2. Multiplication (array_1_col * array_2):
[[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]

3. Subtraction (array_1_col - array_2):
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]
 [ 3  2  1]
 [ 4  3  2]]

4. Division (array_1_col / array_2):
[[1.         0.5        0.33333333]
 [2.         1.         0.66666667]
 [3.         1.5        1.        ]
 [4.         2.         1.33333333]
 [5.         2.5        1.66666667]]

Output matrix shape: (5, 3)
Output matrix dtype: int8
